-keep class com.brycewg.asrkb.imebridge.ImeBridgeHook { *; }
-keep class com.brycewg.asrkb.imebridge.BridgeVisualPrefsProvider { *; }
-keep class com.brycewg.asrkb.imebridge.BridgeVisualPrefs { *; }
-keep class com.brycewg.asrkb.imebridge.BridgeVisualPrefs$VisualConfig { *; }
-keep class com.brycewg.asrkb.imebridge.BridgeContract { *; }
